In [22]:
import pandas as pd

In [28]:
df = pd.read_csv('result/results.csv')
df[[' ', 'train', ' ', 'test']] = df['name'].str.split('_', expand=True)

In [29]:
res = df[['train', 'test', 'threshold_0.5 (all)', 'threshold_0.95 (all)', 'mAP (all)', 'mAP (seg)']]

In [30]:
res

  train test  threshold_0.5 (all)  threshold_0.95 (all)  mAP (all)  mAP (seg)
0   doc  doc             0.763277              0.680911   0.075046   0.309853
1   doc  pub             0.638708              0.544784   0.114541   0.366053
2   pub  doc             0.676548              0.582779   0.034164   0.235736
3   pub  pub             0.707738              0.648074   0.237918   0.454132

In [38]:
col_names = ['threshold_0.5 (all)', 'threshold_0.95 (all)', 'mAP (all)', 'mAP (seg)']
for col in col_names:
    res_mini = res[['train', 'test', col]]
    agr = pd.pivot_table(res_mini, columns=['test'], index=['train'])
    print('-'*40)
    print(agr)

----------------------------------------
      threshold_0.5 (all)
test                  doc       pub
train
doc              0.763277  0.638708
pub              0.676548  0.707738
----------------------------------------
      threshold_0.95 (all)
test                   doc       pub
train
doc               0.680911  0.544784
pub               0.582779  0.648074
----------------------------------------
      mAP (all)
test        doc       pub
train
doc    0.075046  0.114541
pub    0.034164  0.237918
----------------------------------------
      mAP (seg)
test        doc       pub
train
doc    0.309853  0.366053
pub    0.235736  0.454132

In [16]:
res

,name,threshold_0.5 (all),threshold_0.95 (all),mAP (all),mAP (seg),train,test
0,train_doc_test_doc,0.763277,0.680911,0.075046,0.309853,train,train
1,train_doc_test_pub,0.638708,0.544784,0.114541,0.366053,doc,pub
2,train_pub_test_doc,0.676548,0.582779,0.034164,0.235736,test,test
3,train_pub_test_pub,0.707738,0.648074,0.237918,0.454132,pub,pub